name: test
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        go: ["1.24"]

    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        cache: true
        cache-dependency-path: |
          **/go.sum
          **/go.mod

    - name: Install Dependencies
      run: go mod download

    - name: Run Build
      run: make build

    - name: Run Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1

    - name: Run Test
      run: make test
